# Generated by Django 4.0.6 on 2022-07-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment_update_time',
            field=models.DateTimeField(null=True),
        ),
    ]
