# Generated by Django 4.0.6 on 2022-07-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_post_comment_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reddit_locked',
            field=models.BooleanField(default=False),
        ),
    ]
