# Generated by Django 4.0.6 on 2022-10-17 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_post_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField()),
                ('tag', models.TextField()),
                ('value', models.BooleanField(default=False)),
            ],
        ),
    ]
