# Generated by Django 4.0.6 on 2022-10-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_reputation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_asocial',
            field=models.BooleanField(default=False, verbose_name='Show asocial'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_political_junkie',
            field=models.BooleanField(default=False, verbose_name='Show political_junkie'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_reddit_removed',
            field=models.BooleanField(default=False, verbose_name='Show reddit_removed'),
        ),
        migrations.AddConstraint(
            model_name='reputation',
            constraint=models.UniqueConstraint(fields=('user_name', 'tag'), name='unique_user_name_tag_combination'),
        ),
    ]
